-- =====================================================
-- Kraken Intelligence Agent
-- Step 5: Analytical Views
-- =====================================================

USE DATABASE KRAKEN_DB;
USE SCHEMA ANALYTICS;
USE WAREHOUSE KRAKEN_WH;

-- =====================================================
-- VW_TRADING_SUMMARY - Daily trading metrics per pair
-- =====================================================
CREATE OR REPLACE VIEW VW_TRADING_SUMMARY AS
SELECT
    DATE_TRUNC('day', T.EXECUTED_AT) AS TRADE_DATE,
    T.TRADING_PAIR,
    T.TRADE_TYPE,
    COUNT(*) AS TRADE_COUNT,
    COUNT(DISTINCT T.CUSTOMER_ID) AS UNIQUE_TRADERS,
    SUM(T.TOTAL_VALUE_USD) AS TOTAL_VOLUME_USD,
    AVG(T.TOTAL_VALUE_USD) AS AVG_TRADE_SIZE_USD,
    SUM(T.FEE_USD) AS TOTAL_FEES_USD,
    AVG(T.PRICE) AS AVG_PRICE,
    SUM(CASE WHEN T.SIDE = 'Buy' THEN T.TOTAL_VALUE_USD ELSE 0 END) AS BUY_VOLUME_USD,
    SUM(CASE WHEN T.SIDE = 'Sell' THEN T.TOTAL_VALUE_USD ELSE 0 END) AS SELL_VOLUME_USD,
    RATIO_TO_REPORT(SUM(T.TOTAL_VALUE_USD)) OVER (PARTITION BY DATE_TRUNC('day', T.EXECUTED_AT)) AS PAIR_VOLUME_SHARE
FROM KRAKEN_DB.RAW.TRADES T
WHERE T.SETTLEMENT_STATUS = 'Settled'
GROUP BY 1, 2, 3;

-- =====================================================
-- VW_CUSTOMER_360 - Full customer profile summary
-- =====================================================
CREATE OR REPLACE VIEW VW_CUSTOMER_360 AS
SELECT
    C.CUSTOMER_ID,
    C.USERNAME,
    C.FULL_NAME,
    C.ACCOUNT_TIER,
    C.KYC_STATUS,
    C.COUNTRY_CODE,
    C.REGISTRATION_DATE,
    C.IS_ACTIVE,
    C.TOTAL_DEPOSITS_USD,
    C.TOTAL_WITHDRAWALS_USD,
    C.ACCOUNT_BALANCE_USD,
    DATEDIFF('day', C.REGISTRATION_DATE, CURRENT_TIMESTAMP()) AS ACCOUNT_AGE_DAYS,
    DATEDIFF('day', C.LAST_LOGIN_DATE, CURRENT_TIMESTAMP()) AS DAYS_SINCE_LAST_LOGIN,
    -- Trade metrics
    COALESCE(TM.TOTAL_TRADES, 0) AS TOTAL_TRADES,
    COALESCE(TM.TOTAL_VOLUME_USD, 0) AS TOTAL_TRADE_VOLUME_USD,
    COALESCE(TM.TOTAL_FEES_PAID_USD, 0) AS TOTAL_FEES_PAID_USD,
    COALESCE(TM.LAST_TRADE_DATE, C.REGISTRATION_DATE) AS LAST_TRADE_DATE,
    COALESCE(TM.AVG_TRADE_SIZE_USD, 0) AS AVG_TRADE_SIZE_USD,
    COALESCE(TM.DISTINCT_PAIRS_TRADED, 0) AS DISTINCT_PAIRS_TRADED,
    -- Support metrics
    COALESCE(SM.TOTAL_TICKETS, 0) AS TOTAL_SUPPORT_TICKETS,
    COALESCE(SM.OPEN_TICKETS, 0) AS OPEN_TICKETS,
    COALESCE(SM.AVG_SATISFACTION, 0) AS AVG_SATISFACTION_SCORE,
    -- Compliance
    COALESCE(CM.COMPLIANCE_EVENTS, 0) AS TOTAL_COMPLIANCE_EVENTS,
    COALESCE(CM.FLAGGED_EVENTS, 0) AS FLAGGED_EVENTS,
    COALESCE(CM.MAX_RISK_SCORE, 0) AS MAX_RISK_SCORE,
    -- Staking
    COALESCE(SK.ACTIVE_POSITIONS, 0) AS ACTIVE_STAKING_POSITIONS,
    COALESCE(SK.TOTAL_STAKED_USD, 0) AS TOTAL_STAKED_VALUE_USD,
    COALESCE(SK.TOTAL_REWARDS_USD, 0) AS TOTAL_STAKING_REWARDS_USD
FROM KRAKEN_DB.RAW.CUSTOMERS C
LEFT JOIN (
    SELECT 
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_TRADES,
        SUM(TOTAL_VALUE_USD) AS TOTAL_VOLUME_USD,
        SUM(FEE_USD) AS TOTAL_FEES_PAID_USD,
        MAX(EXECUTED_AT) AS LAST_TRADE_DATE,
        AVG(TOTAL_VALUE_USD) AS AVG_TRADE_SIZE_USD,
        COUNT(DISTINCT TRADING_PAIR) AS DISTINCT_PAIRS_TRADED
    FROM KRAKEN_DB.RAW.TRADES
    GROUP BY CUSTOMER_ID
) TM ON C.CUSTOMER_ID = TM.CUSTOMER_ID
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS TOTAL_TICKETS,
        SUM(CASE WHEN STATUS IN ('Open','In Progress','Waiting') THEN 1 ELSE 0 END) AS OPEN_TICKETS,
        AVG(SATISFACTION_SCORE) AS AVG_SATISFACTION
    FROM KRAKEN_DB.RAW.SUPPORT_TICKETS
    GROUP BY CUSTOMER_ID
) SM ON C.CUSTOMER_ID = SM.CUSTOMER_ID
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS COMPLIANCE_EVENTS,
        SUM(CASE WHEN IS_FLAGGED THEN 1 ELSE 0 END) AS FLAGGED_EVENTS,
        MAX(RISK_SCORE) AS MAX_RISK_SCORE
    FROM KRAKEN_DB.RAW.COMPLIANCE_EVENTS
    GROUP BY CUSTOMER_ID
) CM ON C.CUSTOMER_ID = CM.CUSTOMER_ID
LEFT JOIN (
    SELECT
        CUSTOMER_ID,
        COUNT(*) AS ACTIVE_POSITIONS,
        SUM(STAKED_VALUE_USD) AS TOTAL_STAKED_USD,
        SUM(REWARDS_VALUE_USD) AS TOTAL_REWARDS_USD
    FROM KRAKEN_DB.RAW.STAKING_POSITIONS
    WHERE STATUS = 'Active'
    GROUP BY CUSTOMER_ID
) SK ON C.CUSTOMER_ID = SK.CUSTOMER_ID;

-- =====================================================
-- VW_COMPLIANCE_DASHBOARD - Compliance overview metrics
-- =====================================================
CREATE OR REPLACE VIEW VW_COMPLIANCE_DASHBOARD AS
SELECT
    DATE_TRUNC('day', CE.CREATED_AT) AS EVENT_DATE,
    CE.EVENT_TYPE,
    CE.RISK_LEVEL,
    CE.JURISDICTION,
    COUNT(*) AS EVENT_COUNT,
    AVG(CE.RISK_SCORE) AS AVG_RISK_SCORE,
    SUM(CASE WHEN CE.IS_FLAGGED THEN 1 ELSE 0 END) AS FLAGGED_COUNT,
    SUM(CASE WHEN CE.REVIEW_STATUS = 'Pending' THEN 1 ELSE 0 END) AS PENDING_REVIEW,
    SUM(CASE WHEN CE.REVIEW_STATUS = 'Escalated' THEN 1 ELSE 0 END) AS ESCALATED_COUNT,
    SUM(CASE WHEN CE.REGULATORY_REPORT_FILED THEN 1 ELSE 0 END) AS REPORTS_FILED
FROM KRAKEN_DB.RAW.COMPLIANCE_EVENTS CE
GROUP BY 1, 2, 3, 4;

-- =====================================================
-- VW_SUPPORT_METRICS - Support team performance
-- =====================================================
CREATE OR REPLACE VIEW VW_SUPPORT_METRICS AS
SELECT
    DATE_TRUNC('day', ST.CREATED_AT) AS TICKET_DATE,
    ST.CATEGORY,
    ST.PRIORITY,
    ST.ASSIGNED_TEAM,
    COUNT(*) AS TICKET_COUNT,
    SUM(CASE WHEN ST.STATUS IN ('Open','In Progress','Waiting') THEN 1 ELSE 0 END) AS OPEN_TICKETS,
    SUM(CASE WHEN ST.STATUS IN ('Resolved','Closed') THEN 1 ELSE 0 END) AS RESOLVED_TICKETS,
    AVG(ST.FIRST_RESPONSE_MINUTES) AS AVG_FIRST_RESPONSE_MIN,
    AVG(ST.RESOLUTION_MINUTES) AS AVG_RESOLUTION_MIN,
    AVG(ST.SATISFACTION_SCORE) AS AVG_CSAT,
    PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY ST.RESOLUTION_MINUTES) AS MEDIAN_RESOLUTION_MIN,
    PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY ST.RESOLUTION_MINUTES) AS P95_RESOLUTION_MIN
FROM KRAKEN_DB.RAW.SUPPORT_TICKETS ST
GROUP BY 1, 2, 3, 4;

-- =====================================================
-- VW_REVENUE_ANALYTICS - Revenue and fee analysis
-- =====================================================
CREATE OR REPLACE VIEW VW_REVENUE_ANALYTICS AS
SELECT
    DATE_TRUNC('day', T.EXECUTED_AT) AS REVENUE_DATE,
    T.TRADING_PAIR,
    C.ACCOUNT_TIER,
    C.COUNTRY_CODE,
    T.PLATFORM,
    COUNT(*) AS TRADE_COUNT,
    SUM(T.FEE_USD) AS TOTAL_FEES_USD,
    AVG(T.FEE_RATE) AS AVG_FEE_RATE,
    SUM(T.TOTAL_VALUE_USD) AS TOTAL_VOLUME_USD,
    SUM(T.FEE_USD) / NULLIF(SUM(T.TOTAL_VALUE_USD), 0) AS EFFECTIVE_FEE_RATE
FROM KRAKEN_DB.RAW.TRADES T
JOIN KRAKEN_DB.RAW.CUSTOMERS C ON T.CUSTOMER_ID = C.CUSTOMER_ID
WHERE T.SETTLEMENT_STATUS = 'Settled'
GROUP BY 1, 2, 3, 4, 5;

-- =====================================================
-- VW_MARKET_OVERVIEW - Current market state
-- =====================================================
CREATE OR REPLACE VIEW VW_MARKET_OVERVIEW AS
WITH LATEST_PRICES AS (
    SELECT
        TRADING_PAIR,
        CLOSE_PRICE AS CURRENT_PRICE,
        VOLUME_USD AS HOURLY_VOLUME_USD,
        TRADE_COUNT AS HOURLY_TRADES,
        ROW_NUMBER() OVER (PARTITION BY TRADING_PAIR ORDER BY TIMESTAMP DESC) AS RN
    FROM KRAKEN_DB.RAW.MARKET_DATA
    WHERE INTERVAL = '1h'
),
DAILY_STATS AS (
    SELECT
        TRADING_PAIR,
        MAX(HIGH_PRICE) AS HIGH_24H,
        MIN(LOW_PRICE) AS LOW_24H,
        SUM(VOLUME_USD) AS VOLUME_24H_USD,
        SUM(TRADE_COUNT) AS TRADES_24H
    FROM KRAKEN_DB.RAW.MARKET_DATA
    WHERE INTERVAL = '1h' AND TIMESTAMP >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
    GROUP BY TRADING_PAIR
)
SELECT
    LP.TRADING_PAIR,
    LP.CURRENT_PRICE,
    LP.HOURLY_VOLUME_USD,
    LP.HOURLY_TRADES,
    DS.HIGH_24H,
    DS.LOW_24H,
    DS.VOLUME_24H_USD,
    DS.TRADES_24H,
    ROUND((LP.CURRENT_PRICE - DS.LOW_24H) / NULLIF(DS.HIGH_24H - DS.LOW_24H, 0) * 100, 2) AS PRICE_POSITION_PCT
FROM LATEST_PRICES LP
JOIN DAILY_STATS DS ON LP.TRADING_PAIR = DS.TRADING_PAIR
WHERE LP.RN = 1;

-- =====================================================
-- VW_STAKING_OVERVIEW - Staking program metrics
-- =====================================================
CREATE OR REPLACE VIEW VW_STAKING_OVERVIEW AS
SELECT
    SP.ASSET_SYMBOL,
    COUNT(*) AS TOTAL_POSITIONS,
    SUM(CASE WHEN SP.STATUS = 'Active' THEN 1 ELSE 0 END) AS ACTIVE_POSITIONS,
    SUM(SP.STAKED_VALUE_USD) AS TOTAL_STAKED_USD,
    AVG(SP.APY_RATE) AS AVG_APY,
    SUM(SP.REWARDS_VALUE_USD) AS TOTAL_REWARDS_PAID_USD,
    COUNT(DISTINCT SP.CUSTOMER_ID) AS UNIQUE_STAKERS
FROM KRAKEN_DB.RAW.STAKING_POSITIONS SP
GROUP BY SP.ASSET_SYMBOL;

SELECT 'Step 5 Complete: All analytical views created in KRAKEN_DB.ANALYTICS schema.' AS STATUS;
